# Generated by Django 3.1.13 on 2022-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_auto_20220105_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='business_owner',
            field=models.CharField(default=14, max_length=100),
            preserve_default=False,
        ),
    ]
